//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1291163_MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingEntry
    {
        public int bookingEntryId { get; set; }
        public int guestsId { get; set; }
        public int roomId { get; set; }
    
        public virtual guests guests { get; set; }
        public virtual room room { get; set; }
    }
}
