//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1291163_MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class guests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guests()
        {
            this.bookingEntries = new HashSet<bookingEntry>();
        }
    
        public int guestsId { get; set; }
        [Display(Name = "Guest Name")]
        [Required]
        public string guestsName { get; set; }
        [Display(Name = "Booking Date")]
        [DataType(DataType.Date)]
        [FutureDate(ErrorMessage = "Booking date cannot be in the past.")]
        [Required]
        public System.DateTime bookingDate { get; set; }
        [Display(Name = "Number of Guests")]
        [Required]
        public int numberOfGueist { get; set; }
        [Display(Name = "Picture")]
        [Required]
        public string picture { get; set; }
        [Display(Name = "Couple Status")]
        public bool coupleStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingEntry> bookingEntries { get; set; }=new List<bookingEntry>();
    }
}
